Refactoring tb_client
Earendil95/yandex-request-forwarder pull request #7
Opened 2017-06-14 12:57 UTC by paderinandrey

2017-06-14 14:16 UTC, StanisLove commented
approved

2017-06-14 14:24 UTC, Earendil95 requested changes

2017-06-14 14:24 UTC, Earendil95 commented on routes/internal_routes.rb
> +  class InternalRoutes < Cuba
Очень много кода дублируется по сравнению с `routes/client_routes`. Кажется, в объекте `Rack::Request` должна быть информация о path или url, с которым работаем -- можно по ней решать, на какой путь делать запрос в TB и что отправлять в Slack

2017-06-14 14:24 UTC, Earendil95 commented on lib/teachbase_client.rb
> +    end
Отступы исправить)

2017-06-14 14:24 UTC, Earendil95 commented on lib/rrlogger.rb
> +    "Order id: #{req.params["orderNumber"]}\n"
👍

2017-06-14 14:55 UTC, alexsdev91 requested changes

2017-06-14 14:55 UTC, alekseenkoss77 commented on lib/teachbase_client.rb
> +  def check_order(path, params)
метод `check_order` и `payment_aviso` слишком одинаковы, нужно добавить один private метод, который будет делать запрос, и вызывать его в этих методах, т.е сделать их _интерфейсными_

2017-06-14 14:55 UTC, alekseenkoss77 commented on routes/client_routes.rb
> +  class ClientRoutes < Cuba
лучше назвать `ClientController`, т.к роутинга здесь по-сути кот наплакал, а вот логики много.

2017-06-14 14:55 UTC, alekseenkoss77 commented on routes/client_routes.rb
> +              response = check_order("yandex/check_order", req.params)
Опять же, у тебя много кода который повторяется в `check_order` и `payment_aviso`. По-сути различия только в вызове метода и в slack_post аргументе. Можно это вынести в отдельный метод и вызывать его, а вот ему уже аргументом передать `payment_method`, который будет `:payment_aviso` или `:check_order`, которые уже вызывать через `public_send`

2017-06-14 14:55 UTC, alekseenkoss77 commented on routes/client_routes.rb
> +              response = check_order("yandex/check_order", req.params)
Кстати можно сделать прикольнее. Оставим этот класс как Route, вот в роутах можно вызывать другой класс уже контроллер (т.е. сделать еще один), в котором будет уже _вся_ бизнес-логика.

2017-06-14 14:55 UTC, alekseenkoss77 commented on routes/internal_routes.rb
> +  class InternalRoutes < Cuba
Да. По-сути можно все запаковать в один класс, контроллера, который использовать в классах-роутерах.

2017-06-14 14:55 UTC, alekseenkoss77 commented on lib/rrlogger.rb
> +    "Order id: #{req.params["orderNumber"]}\n"
одинарные кавычки

2017-06-18 16:26 UTC, Earendil95 approved these changes

2017-06-27 09:58 UTC, closed without merging